export const constLanguageInfoArray: typeLanguageInfo[] = [
  {
    code: "ar-SA",
    language: "Arabic",
    country: "Saudi Arabia",
    description: "Arabic (Saudi Arabia)",
  },
  {
    code: "bn-BD",
    language: "Bangla",
    country: "Bangladesh",
    description: "Bangla (Bangladesh)",
  },
  {
    code: "bn-IN",
    language: "Bangla",
    country: "India",
    description: "Bangla (India)",
  },
  {
    code: "cs-CZ",
    language: "Czech",
    country: "Czech Republic",
    description: "Czech (Czech Republic)",
  },
  {
    code: "da-DK",
    language: "Danish",
    country: "Denmark",
    description: "Danish (Denmark)",
  },
  {
    code: "de-AT",
    language: "German",
    country: "Austria",
    description: "Austrian German",
  },
  {
    code: "de-CH",
    language: "German",
    country: "Switzerland",
    description: '"Swiss" German',
  },
  {
    code: "de-DE",
    language: "German",
    country: "Germany",
    description: "Standard German (as spoken in Germany)",
  },
  {
    code: "el-GR",
    language: "Greek",
    country: "Greece",
    description: "Modern Greek",
  },
  {
    code: "en-AU",
    language: "English",
    country: "Australia",
    description: "Australian English",
  },
  {
    code: "en-CA",
    language: "English",
    country: "Canada",
    description: "Canadian English",
  },
  {
    code: "en-GB",
    language: "English",
    country: "United Kingdom",
    description: "British English",
  },
  {
    code: "en-IE",
    language: "English",
    country: "Ireland",
    description: "Irish English",
  },
  {
    code: "en-IN",
    language: "English",
    country: "India",
    description: "Indian English",
  },
  {
    code: "en-NZ",
    language: "English",
    country: "New Zealand",
    description: "New Zealand English",
  },
  {
    code: "en-US",
    language: "English",
    country: "United States",
    description: "US English",
  },
  {
    code: "en-ZA",
    language: "English",
    country: "South Africa",
    description: "English (South Africa)",
  },
  {
    code: "es-AR",
    language: "Spanish",
    country: "Argentina",
    description: "Argentine Spanish",
  },
  {
    code: "es-CL",
    language: "Spanish",
    country: "Chile",
    description: "Chilean Spanish",
  },
  {
    code: "es-CO",
    language: "Spanish",
    country: "Columbia",
    description: "Colombian Spanish",
  },
  {
    code: "es-ES",
    language: "Spanish",
    country: "Spain",
    description: "Castilian Spanish (as spoken in Central-Northern Spain)",
  },
  {
    code: "es-MX",
    language: "Spanish",
    country: "Mexico",
    description: "Mexican Spanish",
  },
  {
    code: "es-US",
    language: "Spanish",
    country: "United States",
    description: "American Spanish",
  },
  {
    code: "fi-FI",
    language: "Finnish",
    country: "Finland",
    description: "Finnish (Finland)",
  },
  {
    code: "fr-BE",
    language: "French",
    country: "Belgium",
    description: "Belgian French",
  },
  {
    code: "fr-CA",
    language: "French",
    country: "Canada",
    description: "Canadian French",
  },
  {
    code: "fr-CH",
    language: "French",
    country: "Switzerland",
    description: '"Swiss" French',
  },
  {
    code: "fr-FR",
    language: "French",
    country: "France",
    description: "Standard French (especially in France)",
  },
  {
    code: "he-IL",
    language: "Hebrew",
    country: "Israel",
    description: "Hebrew (Israel)",
  },
  {
    code: "hi-IN",
    language: "Hindi",
    country: "India",
    description: "Hindi (India)",
  },
  {
    code: "hu-HU",
    language: "Hungarian",
    country: "Hungary",
    description: "Hungarian (Hungary)",
  },
  {
    code: "id-ID",
    language: "Indonesian",
    country: "Indonesia",
    description: "Indonesian (Indonesia)",
  },
  {
    code: "it-CH",
    language: "Italian",
    country: "Switzerland",
    description: '"Swiss" Italian',
  },
  {
    code: "it-IT",
    language: "Italian",
    country: "Italy",
    description: "Standard Italian (as spoken in Italy)",
  },
  {
    code: "jp-JP",
    language: "Japanese",
    country: "Japan",
    description: "Japanese (Japan)",
  },
  {
    code: "ko-KR",
    language: "Korean",
    country: "Republic of Korea",
    description: "Korean (Republic of Korea)",
  },
  {
    code: "nl-BE",
    language: "Dutch",
    country: "Belgium",
    description: "Belgian Dutch",
  },
  {
    code: "nl-NL",
    language: "Dutch",
    country: "The Netherlands",
    description: "Standard Dutch (as spoken in The Netherlands)",
  },
  {
    code: "no-NO",
    language: "Norwegian",
    country: "Norway",
    description: "Norwegian (Norway)",
  },
  {
    code: "pl-PL",
    language: "Polish",
    country: "Poland",
    description: "Polish (Poland)",
  },
  {
    code: "pt-BR",
    language: "Portuguese",
    country: "Brazil",
    description: "Brazilian Portuguese",
  },
  {
    code: "pt-PT",
    language: "Portuguese",
    country: "Portugal",
    description: "European Portuguese (as written and spoken in Portugal)",
  },
  {
    code: "ro-RO",
    language: "Romanian",
    country: "Romania",
    description: "Romanian (Romania)",
  },
  {
    code: "ru-RU",
    language: "Russian",
    country: "Russian Federation",
    description: "Russian (Russian Federation)",
  },
  {
    code: "sk-SK",
    language: "Slovak",
    country: "Slovakia",
    description: "Slovak (Slovakia)",
  },
  {
    code: "sv-SE",
    language: "Swedish",
    country: "Sweden",
    description: "Swedish (Sweden)",
  },
  {
    code: "ta-IN",
    language: "Tamil",
    country: "India",
    description: "Indian Tamil",
  },
  {
    code: "ta-LK",
    language: "Tamil",
    country: "Sri Lanka",
    description: "Sri Lankan Tamil",
  },
  {
    code: "th-TH",
    language: "Thai",
    country: "Thailand",
    description: "Thai (Thailand)",
  },
  {
    code: "tr-TR",
    language: "Turkish",
    country: "Turkey",
    description: "Turkish (Turkey)",
  },
  {
    code: "zh-CN",
    language: "Chinese",
    country: "China",
    description: "Mainland China, simplified characters",
  },
  {
    code: "zh-HK",
    language: "Chinese",
    country: "Hong Kong",
    description: "Hong Kong, traditional characters",
  },
  {
    code: "zh-TW",
    language: "Chinese",
    country: "Taiwan",
    description: "Taiwan, traditional characters",
  },
];

export const constLanguagesObject: Record<string, typeLanguageInfo> = {
  ar_SA: {
    code: "ar-SA",
    language: "Arabic",
    country: "Saudi Arabia",
    description: "Arabic (Saudi Arabia)",
  },
  bn_BD: {
    code: "bn-BD",
    language: "Bangla",
    country: "Bangladesh",
    description: "Bangla (Bangladesh)",
  },
  bn_IN: {
    code: "bn-IN",
    language: "Bangla",
    country: "India",
    description: "Bangla (India)",
  },
  cs_CZ: {
    code: "cs-CZ",
    language: "Czech",
    country: "Czech Republic",
    description: "Czech (Czech Republic)",
  },
  da_DK: {
    code: "da-DK",
    language: "Danish",
    country: "Denmark",
    description: "Danish (Denmark)",
  },
  de_AT: {
    code: "de-AT",
    language: "German",
    country: "Austria",
    description: "Austrian German",
  },
  de_CH: {
    code: "de-CH",
    language: "German",
    country: "Switzerland",
    description: '"Swiss" German',
  },
  de_DE: {
    code: "de-DE",
    language: "German",
    country: "Germany",
    description: "Standard German (as spoken in Germany)",
  },
  el_GR: {
    code: "el-GR",
    language: "Greek",
    country: "Greece",
    description: "Modern Greek",
  },
  en_AU: {
    code: "en-AU",
    language: "English",
    country: "Australia",
    description: "Australian English",
  },
  en_CA: {
    code: "en-CA",
    language: "English",
    country: "Canada",
    description: "Canadian English",
  },
  en_GB: {
    code: "en-GB",
    language: "English",
    country: "United Kingdom",
    description: "British English",
  },
  en_IE: {
    code: "en-IE",
    language: "English",
    country: "Ireland",
    description: "Irish English",
  },
  en_IN: {
    code: "en-IN",
    language: "English",
    country: "India",
    description: "Indian English",
  },
  en_NZ: {
    code: "en-NZ",
    language: "English",
    country: "New Zealand",
    description: "New Zealand English",
  },
  en_US: {
    code: "en-US",
    language: "English",
    country: "United States",
    description: "US English",
  },
  en_ZA: {
    code: "en-ZA",
    language: "English",
    country: "South Africa",
    description: "English (South Africa)",
  },
  es_AR: {
    code: "es-AR",
    language: "Spanish",
    country: "Argentina",
    description: "Argentine Spanish",
  },
  es_CL: {
    code: "es-CL",
    language: "Spanish",
    country: "Chile",
    description: "Chilean Spanish",
  },
  es_CO: {
    code: "es-CO",
    language: "Spanish",
    country: "Colombia",
    description: "Colombian Spanish",
  },
  es_ES: {
    code: "es-ES",
    language: "Spanish",
    country: "Spain",
    description: "Castilian Spanish (as spoken in Central-Northern Spain)",
  },
  es_MX: {
    code: "es-MX",
    language: "Spanish",
    country: "Mexico",
    description: "Mexican Spanish",
  },
  es_US: {
    code: "es-US",
    language: "Spanish",
    country: "United States",
    description: "American Spanish",
  },
  fi_FI: {
    code: "fi-FI",
    language: "Finnish",
    country: "Finland",
    description: "Finnish (Finland)",
  },
  fr_BE: {
    code: "fr-BE",
    language: "French",
    country: "Belgium",
    description: "Belgian French",
  },
  fr_CA: {
    code: "fr-CA",
    language: "French",
    country: "Canada",
    description: "Canadian French",
  },
  fr_CH: {
    code: "fr-CH",
    language: "French",
    country: "Switzerland",
    description: '"Swiss" French',
  },
  fr_FR: {
    code: "fr-FR",
    language: "French",
    country: "France",
    description: "Standard French (especially in France)",
  },
  he_IL: {
    code: "he-IL",
    language: "Hebrew",
    country: "Israel",
    description: "Hebrew (Israel)",
  },
  hi_IN: {
    code: "hi-IN",
    language: "Hindi",
    country: "India",
    description: "Hindi (India)",
  },
  hu_HU: {
    code: "hu-HU",
    language: "Hungarian",
    country: "Hungary",
    description: "Hungarian (Hungary)",
  },
  id_ID: {
    code: "id-ID",
    language: "Indonesian",
    country: "Indonesia",
    description: "Indonesian (Indonesia)",
  },
  it_CH: {
    code: "it-CH",
    language: "Italian",
    country: "Switzerland",
    description: '"Swiss" Italian',
  },
  it_IT: {
    code: "it-IT",
    language: "Italian",
    country: "Italy",
    description: "Standard Italian (as spoken in Italy)",
  },
  jp_JP: {
    code: "jp-JP",
    language: "Japanese",
    country: "Japan",
    description: "Japanese (Japan)",
  },
  ko_KR: {
    code: "ko-KR",
    language: "Korean",
    country: "Republic of Korea",
    description: "Korean (Republic of Korea)",
  },
  nl_BE: {
    code: "nl-BE",
    language: "Dutch",
    country: "Belgium",
    description: "Belgian Dutch",
  },
  nl_NL: {
    code: "nl-NL",
    language: "Dutch",
    country: "The Netherlands",
    description: "Standard Dutch (as spoken in The Netherlands)",
  },
  no_NO: {
    code: "no-NO",
    language: "Norwegian",
    country: "Norway",
    description: "Norwegian (Norway)",
  },
  pl_PL: {
    code: "pl-PL",
    language: "Polish",
    country: "Poland",
    description: "Polish (Poland)",
  },
  pt_BR: {
    code: "pt-BR",
    language: "Portuguese",
    country: "Brazil",
    description: "Brazilian Portuguese",
  },
  pt_PT: {
    code: "pt-PT",
    language: "Portuguese",
    country: "Portugal",
    description: "European Portuguese (as written and spoken in Portugal)",
  },
  ro_RO: {
    code: "ro-RO",
    language: "Romanian",
    country: "Romania",
    description: "Romanian (Romania)",
  },
  ru_RU: {
    code: "ru-RU",
    language: "Russian",
    country: "Russian Federation",
    description: "Russian (Russian Federation)",
  },
  sk_SK: {
    code: "sk-SK",
    language: "Slovak",
    country: "Slovakia",
    description: "Slovak (Slovakia)",
  },
  sv_SE: {
    code: "sv-SE",
    language: "Swedish",
    country: "Sweden",
    description: "Swedish (Sweden)",
  },
  ta_IN: {
    code: "ta-IN",
    language: "Tamil",
    country: "India",
    description: "Indian Tamil",
  },
  ta_LK: {
    code: "ta-LK",
    language: "Tamil",
    country: "Sri Lanka",
    description: "Sri Lankan Tamil",
  },
  th_TH: {
    code: "th-TH",
    language: "Thai",
    country: "Thailand",
    description: "Thai (Thailand)",
  },
  tr_TR: {
    code: "tr-TR",
    language: "Turkish",
    country: "Turkey",
    description: "Turkish (Turkey)",
  },
  zh_CN: {
    code: "zh-CN",
    language: "Chinese",
    country: "China",
    description: "Mainland China, simplified characters",
  },
  zh_HK: {
    code: "zh-HK",
    language: "Chinese",
    country: "Hong Kong",
    description: "Hong Kong, traditional characters",
  },
  zh_TW: {
    code: "zh-TW",
    language: "Chinese",
    country: "Taiwan",
    description: "Taiwan, traditional characters",
  },
};
